nft mint table
FlipsideCrypto/near-models pull request #155
Opened 2023-05-16 00:39 UTC by WHYTEWYLL

# Description

The NFT mint table is established in accordance with Near's standard, accompanied by a clear definition of what constitutes an NFT.

# Tests

![image](https://github.com/FlipsideCrypto/near-models/assets/49686519/ac808d64-a832-48ef-a4ec-cb9474a73e8c)

2023-05-16 15:52 UTC, forgxyz commented on models/silver/curated/silver__standard_nft_mint_s3.sql
> +ORDER BY
Ordering is not necessary

2023-05-16 15:56 UTC, forgxyz commented on models/silver/curated/silver__standard_nft_mint_s3.sql
> +    ORDER BY
Ordering is not necessary

2023-05-16 15:57 UTC, forgxyz commented on models/silver/curated/silver__standard_nft_mint_s3.sql
> +        clean_log :data AS DATA,
Looks like this CTE is just extracting from the log json. This can probably be done in the `standard_logs` json, unless you ran into errors with the where clause

2023-05-16 15:59 UTC, forgxyz commented on models/silver/curated/silver__standard_nft_mint_s3.sql
> +        ) AS owner_per_txns,
Other models use `tx` rather than `txn` or `txns` as shorthand for transaction so we should be consistent

2023-05-16 16:00 UTC, forgxyz commented on models/silver/curated/silver__standard_nft_mint_s3.sql
> +        VALUE AS token_id,
Cast to str

2023-05-16 16:00 UTC, forgxyz commented on models/silver/curated/silver__standard_nft_mint_s3.sql
> +            tokens :: ARRAY
tokens is already cast as an ARRAY in the flatten, so not explicitly necessary, here

2023-05-16 16:01 UTC, forgxyz commented on models/silver/curated/silver__standard_nft_mint_s3.sql
> +        ) AS mint_fee -- // Tgas
Is this mint fee, or just the gas burned by the mint action?
I'd be hesitant to create a new definition, here

2023-05-16 16:05 UTC, forgxyz requested changes
Overall, sound logic. Comments are more on semantics.

2 things we will need to do next:
1. This silver model will replace the current nft mints model in feeding the core view. We can add, but should not reduce columns from that view (`core.fact_nft_mints`). Thus - do we have everything we need?

2. Tests - the data extracted from the json should be tested. This is typically done on the core views (except for cols that need the ingestion buffer, like what you have added).

2023-05-17 05:46 UTC, WHYTEWYLL commented
<img width="1213" alt="image" src="https://github.com/FlipsideCrypto/near-models/assets/49686519/574076e2-cfe6-4a48-95dd-a9e5f8645407">

2023-05-17 16:50 UTC, forgxyz approved these changes

2023-05-17 16:50 UTC, merged