An 3132 near atlas wallets olap
FlipsideCrypto/near-models pull request #160
Opened 2023-05-26 16:43 UTC by WHYTEWYLL

# Description

_Please include a summary of changes and related issue (if any)._

# Tests

- [ ] Please provide evidence of your successful `dbt run` / `dbt test` here
- [ ] Any comparison between `prod` and `dev` for any schema change

# Checklist
- [ ] Follow [dbt style guide](https://github.com/dbt-labs/corp/blob/main/dbt_style_guide.md)
- [ ] Run `git merge main` to pull any changes from remote into your branch prior to merge.
- [ ] Tag the person(s) responsible for reviewing proposed changes
- [ ] **IMPORTANT** Note for deployment if a `full-refresh` is needed for any model this PR impacts.
     - If any schema is changing, whether it be a table or a view, we will need to run a `full-refresh` in prod to avoid errors with the scheduled refresh jobs.
     - The PR can be reviewed, but should not be merged unless by someone with prod access.
         - Tag `forgxyz` if a full-refresh will be required on prod.

2023-06-01 15:32 UTC, forgxyz commented on models/silver/olaf_wallets/silver__olaf_account_owner.sql
> +    distinct receiver_id as receiver_account_id,
Let's keep the column name the same as `receiver_id`

2023-06-01 15:33 UTC, forgxyz commented on models/silver/olaf_wallets/silver__olaf_account_owner.sql
> +    _load_timestamp
keep `_partition_by_block_number` internal column

2023-06-01 15:52 UTC, forgxyz commented on models/silver/olaf_wallets/silver__olaf_activity.sql
> +    LIMIT 20000000
If the full scan takes too long to complete, we should run in batches by the block partition, rather than an arbitrary limit

2023-06-01 15:53 UTC, forgxyz commented on models/silver/olaf_wallets/silver__olaf_activity.sql
> +        a.signer_id as signer_account_id,
Again, let's use the column name as-is rather than creating something new

2023-06-01 15:53 UTC, forgxyz commented on models/silver/olaf_wallets/silver__olaf_activity.sql
> +    tags = ['actions', 'olaf']
OLAP

2023-06-01 15:54 UTC, forgxyz commented on models/silver/olaf_wallets/silver__olaf_activity.sql
> +        CASE WHEN a.action_name = 'FunctionCall' THEN 'FUNCTION_CALL'
No need to rename the methods, here, let's keep the name as-is on chain.

2023-06-01 15:54 UTC, forgxyz commented on models/silver/olaf_wallets/silver__olaf_activity.sql
> +            ELSE 'no_action' END as action_kind,
No need to create a new column name for `action_name`

2023-06-01 16:00 UTC, forgxyz commented on models/silver/olaf_wallets/silver__olaf_activity.sql
> +       count(distinct method_name) as total_actions_taken,
I would call this something else. A method will occur within a FunctionCall action but not others. As you have it written, a transfer or addkey, for example, are not being counted as actions taken. 

Maybe just `total_unique_methods_called`

2023-06-01 16:03 UTC, forgxyz commented on models/silver/olaf_wallets/silver__olaf_activity.sql
> +       count(distinct total_methods_called) as total_methods_called,
The col being counted is distinct method names, which will lead to something like multiple `submit` methods being counted as 1. This is very similar to `total_actions_taken`, then. I would adjust this and how `functioncall` is counted / adjusted above.

2023-06-01 16:03 UTC, forgxyz commented on models/silver/olaf_wallets/silver__olaf_activity.sql
> +       //a.block_timestamp,
If not using, del before final model

2023-06-01 16:06 UTC, forgxyz commented on models/silver/olaf_wallets/silver__olaf_activity.sql
> +       min(a.block_timestamp) as account_created_date,
This won't work with an incremental strategy. When an acct creates a tx in the incrementally loading data, the min block_timestamp will be calculated over the partition of data since the max. Snowflake will then alter the data based on the unique key (signer), and change the account_created_date to a new date

2023-06-01 16:06 UTC, forgxyz commented on models/silver/olaf_wallets/silver__olaf_activity.sql
> +    incremental_strategy = 'delete+insert',
Let's use merge here

2023-06-01 16:13 UTC, forgxyz commented on models/silver/olaf_wallets/silver__olaf_account_owner.sql
> +
I think we may need 1 more CTE to ensure only new accounts are inserted upon the incremental run, adding something like `where receiver_id not in (select receiver_id from self)`

thought process:
 - this will run and account ABC will get a created date of 1/1/2021.
 - if account ABC writes a tx today, that will get scanned during the incremental run
 - this query will take the id, block timestamp, signer, predecessor id, etc from the earliest receipt *in the available data* (i.e. in the current incremental run)
 - the data in the table will be updated based on the unique key which is the acct id
 - as this is more like a dimensional table than it is fact, we do **not** want that updated (regardless of merge or delete+insert)
 - so, the process should be to scan new data incrementally and only append new accounts that are created, not to update past records

2023-06-01 16:14 UTC, forgxyz commented on models/silver/olaf_wallets/silver__olaf_activity.sql
> +       min(a.block_timestamp) as account_created_date,
Further, why are we calculating account created date here when it is already done so in the account owner table?

2023-06-01 16:21 UTC, forgxyz commented on models/silver/olaf_wallets/silver__olaf_activity.sql
> +       count(distinct a.receiver_id) as accounts_transacted_with,
In incremental, this count will apply to the activity since last run. Both merge or delete+insert will cause the prior number to be overwritten, rather than added to.

May need to self-join instead...

2023-06-01 16:21 UTC, forgxyz commented on models/silver/olaf_wallets/silver__olaf_activity_time.sql
> +    tags = ['timeline', 'olaf']
OLAP

2023-06-01 16:22 UTC, forgxyz commented on models/silver/olaf_wallets/silver__olaf_activity_time.sql
> +    min(BLOCK_TIMESTAMP) AS account_created_date
Account created is built in the account owner table, take it from there instead of creating new

2023-06-01 16:23 UTC, forgxyz commented on models/silver/olaf_wallets/silver__olaf_activity_time.sql
> +        count(distinct case when BLOCK_TIMESTAMP between account_created_date and account_created_date + INTERVAL '6 day' then BLOCK_TIMESTAMP end) as days_active_first_7d,
Have not run the model as I think it will take a long time to process. I don't think this will work with an incremental model, as-is.

2023-06-01 16:24 UTC, forgxyz requested changes
Comments throughout, pausing here for discussion over Slack.

 - impact of change to data & logic when run as incremental vs full build needs to be considered
 - rename to OLAP
 - no need to create new column names
 - let's put in a schema called foundation, not silver
 - possibly leave the activity over time out of scope and require the NF use their own logic / query for that

2023-06-02 11:51 UTC, WHYTEWYLL commented on models/silver/olaf_wallets/silver__olaf_activity_time.sql
> +        count(distinct case when BLOCK_TIMESTAMP between account_created_date and account_created_date + INTERVAL '6 day' then BLOCK_TIMESTAMP end) as days_active_first_7d,
Me neither. I think I explained it [here](https://flipsidecrypto.slack.com/archives/D055MUHNQ05/p1685119339725399). My idea was to push it, to iterate on after getting your feedback. Because I needed some help

2023-06-02 12:06 UTC, WHYTEWYLL commented on models/silver/olaf_wallets/silver__olaf_activity_time.sql
> +        count(distinct case when BLOCK_TIMESTAMP between account_created_date and account_created_date + INTERVAL '6 day' then BLOCK_TIMESTAMP end) as days_active_first_7d,
And wanted to pick your brain, in maybe doing it like [this](https://app.snowflake.com/us-east-1/vna27887/w3GOL9rf0Y4W#query) That I also mentioned in that slack message

2023-12-01 18:32 UTC, closed without merging