AN-2754/nft metadata
FlipsideCrypto/near-models pull request #201
Opened 2023-09-14 01:08 UTC by forgxyz

In progress - 

2 LQ models for Pagoda (token-level) and Nearblocks (contract-level) metadata

2023-09-26 17:04 UTC, desmond-hui requested changes

2023-09-26 17:04 UTC, desmond-hui commented on models/silver/livequery/livequery__request_nearblocks_ft_metadata.py
> +                            response,
I think this should be `json.loads(response[0][0])['data']` so that you are actually dumping JSON into a VARIANT data type vs a string that is wrapping two arrays.  The `to_json` function in SF wasn't handling it properly and the innner objects stayed as strings vs you don't need to use `to_json` at all if we use `json.loads` before dumping the data

Check the difference in output between the two versions to see if you agree...The one currently in dev is after using `json.loads`

`select data, _inserted_timestamp
from near_dev.livequery.request_nearblocks_ft_metadata
limit 2;`

2023-09-26 19:43 UTC, forgxyz commented on models/silver/livequery/livequery__request_nearblocks_ft_metadata.py
> +                            response,
Good call, will review and revise

2023-09-27 14:11 UTC, eric-laurello approved these changes

2023-09-27 14:23 UTC, desmond-hui approved these changes

2023-09-27 14:36 UTC, merged