nft sales
FlipsideCrypto/near-models pull request #283
Opened 2024-04-24 14:56 UTC by WHYTEWYLL

2024-04-24 20:05 UTC, WHYTEWYLL commented
- Adding prices as its only near and we have it pretty well covered. Will get updated with V2 prices.
- Fees events are not on chain. Its a fixed cut.

2024-04-29 17:25 UTC, forgxyz commented on models/silver/curated/nft/silver__nft_sales.sql
> +AND modified_timestamp >= (
I think this needs to be _modified_timestamp to properly reference the underlying table

2024-04-29 17:26 UTC, forgxyz commented on models/silver/curated/nft/silver__nft_sales.sql
> +prices_oracle_s3 AS (
Just name CTE prices and we can migrate it to use the coming prices_final model

2024-04-29 17:26 UTC, forgxyz commented on models/silver/curated/nft/silver__nft_sales.sql
> +        price_usd
This needs to be an aggregation of some kind to ensure one price per hour record.

2024-04-29 17:27 UTC, forgxyz commented on models/silver/curated/nft/silver__nft_sales.sql
> +------------------------------- MINBASE  -------------------------------
I believe it's minTbase

2024-04-29 17:28 UTC, forgxyz commented on models/silver/curated/nft/silver__nft_sales.sql
> +        END :: STRING AS seller_address,
Cast dtype inline when indexing into the variant, not at the end of the case statement

2024-04-29 17:30 UTC, forgxyz commented on models/silver/curated/nft/silver__nft_sales.sql
> +        CASE
Instead of multiple case statements, I think we can have a BOOL column
method_name = 'buy' AS is_buy

Then IFF(is_buy, <value if true>, <value if false>) for the subsequent steps, so it is only evaluated once instead of over multiple CASEs

2024-04-29 17:35 UTC, forgxyz commented on models/silver/curated/nft/silver__nft_sales.sql
> +        price * price_usd AS price_usd,
Can you just explicitly reference these columns with s.price and p.price_usd to avoid confusion and any potential future conflict in case the new table has a PRICE column

2024-04-29 17:37 UTC, forgxyz commented on models/silver/curated/nft/silver__nft_sales.sql
> +        action_id,
Let's split out receipt ID from action ID and only have that revealed to users in the gold view as tx hash and receipt(_object_)id are the primary 2 identifiers on near

2024-04-29 22:29 UTC, forgxyz approved these changes

2024-04-30 21:08 UTC, forgxyz requested changes
Add `_partition_by_block_number` and manual fix conditional to silver model

2024-05-02 18:22 UTC, forgxyz approved these changes

2024-05-02 18:24 UTC, merged